- label: "Getting Started"
  items:
      - label: "Getting Deneb"
        link: "/installation"
      - label: "Simple Worked Example"
        link: "/simple-worked-example"
      - label: "Visual Dataset Binding"
        link: "/visual-dataset-binding"
      - label: "Visual Editor"
        link: "/visual-editor"
- label: "Digging Deeper"
  items:
      - label: "Formatting Values"
        link: "/formatting-values"
      - label: "Pattern Fills"
        link: "/pattern-fills"
      - label: Working With Templates
        link: "/templates"
      - label: "Performance Considerations"
        link: "/performance-considerations"
- label: "Interactivity Features"
  items:
      - label: "Interactivity Overview"
        link: "/interactivity-features-overview"
      - label: "Tooltips"
        link: "/interactivity-tooltips"
- label: "Further Resources"
  items:
      - label: Support
        link: /support
      - label: "Privacy Policy"
        link: "/privacy-policy"
      - label: FAQ
        link: "/faq"
      - label: "Change Log"
        link: "/changelog"
      - label: Contributors
        link: /contributors
      - label: Community Examples & Videos
        link: "/community-examples"
      - label: "Vega Documentation"
        link: "https://vega.github.io/vega/docs/"
      - label: "Vega-Lite Documentation"
        link: "http://vega.github.io/vega-lite/docs/"
      - label: "Source Code [GitHub]"
        link: "https://github.com/deneb-viz/deneb"
